### PR TITLE
Skip command

### PR DESCRIPTION
**Pull request by nguyenquangminh0711**
| Command | Default key binding | Alias |
| ------- | ------------------- | ----- |
| `skip [-a -all]` | | |

Continue the execution of your program to the end, and skip one, or more next breakpoints it meets. This command is useful when you puts `jard` command in an iteration or a nested method calls.

**Note:**
Ruby Jard resets skipping list in next attachment, or when your program exits. If you are running a web server, or background jobs that prevent your program from stopping, and you already skip all breakpoints, your program may not stop, and requires a restart to attach again.

**Examples:**

```
skip      # Continue and skip the first breakpoint
```
skip

```
skip 2    # Continue and skip the first 2 breakpoints it meets
```
skip-2

```
skip --all # Continue and skip all breakpoints
```
skip-all

## Others
- Refactor to simplify console management and pipeline.
- Optimize internal threads. Reduce from dozen of internal threads to 3.
- Permanently prevents Jard internal output appears in `jard output` command. 

Resolve issue https://github.com/nguyenquangminh0711/ruby_jard/issues/58

### CODE REVIEW

**Comment by huydx** [comment]
LGTM after test pass

**Review by quannt — APPROVED** [review]
LGTM

**Review by huynhminhtufu — APPROVED** [review]
LGTM

**Comment by ldakhoa** [comment]
LGTM

**Comment by ldhnam** [comment]
LGTM

**Pull request merged**
